server:
  port: 8084
spring:
  application:
    name: livre
  datasource:
    url: 'jdbc:h2:mem:livresdb'
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    config:
      enabled: false
    discovery:
      enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: 'http://localhost:8761/eureka/'
management:
  endpoints:
    web:
      exposure:
        include: '*'